/*
 * 阿波罗客户端
 *
 * 阿波罗客户端
 *
 * API version: v0.0.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Releases struct for Releases
type Releases struct {
	AppId                      *string                 `json:"appId,omitempty"`
	ClusterName                *string                 `json:"clusterName,omitempty"`
	NamespaceName              *string                 `json:"namespaceName,omitempty"`
	Name                       *string                 `json:"name,omitempty"`
	Configurations             *ReleasesConfigurations `json:"configurations,omitempty"`
	Comment                    *string                 `json:"comment,omitempty"`
	DataChangeCreatedBy        *string                 `json:"dataChangeCreatedBy,omitempty"`
	DataChangeLastModifiedBy   *string                 `json:"dataChangeLastModifiedBy,omitempty"`
	DataChangeCreatedTime      *string                 `json:"dataChangeCreatedTime,omitempty"`
	DataChangeLastModifiedTime *string                 `json:"dataChangeLastModifiedTime,omitempty"`
}

// NewReleases instantiates a new Releases object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReleases() *Releases {
	this := Releases{}
	return &this
}

// NewReleasesWithDefaults instantiates a new Releases object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReleasesWithDefaults() *Releases {
	this := Releases{}
	return &this
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *Releases) GetAppId() string {
	if o == nil || o.AppId == nil {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Releases) GetAppIdOk() (*string, bool) {
	if o == nil || o.AppId == nil {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *Releases) HasAppId() bool {
	if o != nil && o.AppId != nil {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *Releases) SetAppId(v string) {
	o.AppId = &v
}

// GetClusterName returns the ClusterName field value if set, zero value otherwise.
func (o *Releases) GetClusterName() string {
	if o == nil || o.ClusterName == nil {
		var ret string
		return ret
	}
	return *o.ClusterName
}

// GetClusterNameOk returns a tuple with the ClusterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Releases) GetClusterNameOk() (*string, bool) {
	if o == nil || o.ClusterName == nil {
		return nil, false
	}
	return o.ClusterName, true
}

// HasClusterName returns a boolean if a field has been set.
func (o *Releases) HasClusterName() bool {
	if o != nil && o.ClusterName != nil {
		return true
	}

	return false
}

// SetClusterName gets a reference to the given string and assigns it to the ClusterName field.
func (o *Releases) SetClusterName(v string) {
	o.ClusterName = &v
}

// GetNamespaceName returns the NamespaceName field value if set, zero value otherwise.
func (o *Releases) GetNamespaceName() string {
	if o == nil || o.NamespaceName == nil {
		var ret string
		return ret
	}
	return *o.NamespaceName
}

// GetNamespaceNameOk returns a tuple with the NamespaceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Releases) GetNamespaceNameOk() (*string, bool) {
	if o == nil || o.NamespaceName == nil {
		return nil, false
	}
	return o.NamespaceName, true
}

// HasNamespaceName returns a boolean if a field has been set.
func (o *Releases) HasNamespaceName() bool {
	if o != nil && o.NamespaceName != nil {
		return true
	}

	return false
}

// SetNamespaceName gets a reference to the given string and assigns it to the NamespaceName field.
func (o *Releases) SetNamespaceName(v string) {
	o.NamespaceName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Releases) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Releases) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Releases) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Releases) SetName(v string) {
	o.Name = &v
}

// GetConfigurations returns the Configurations field value if set, zero value otherwise.
func (o *Releases) GetConfigurations() ReleasesConfigurations {
	if o == nil || o.Configurations == nil {
		var ret ReleasesConfigurations
		return ret
	}
	return *o.Configurations
}

// GetConfigurationsOk returns a tuple with the Configurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Releases) GetConfigurationsOk() (*ReleasesConfigurations, bool) {
	if o == nil || o.Configurations == nil {
		return nil, false
	}
	return o.Configurations, true
}

// HasConfigurations returns a boolean if a field has been set.
func (o *Releases) HasConfigurations() bool {
	if o != nil && o.Configurations != nil {
		return true
	}

	return false
}

// SetConfigurations gets a reference to the given ReleasesConfigurations and assigns it to the Configurations field.
func (o *Releases) SetConfigurations(v ReleasesConfigurations) {
	o.Configurations = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *Releases) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Releases) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *Releases) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *Releases) SetComment(v string) {
	o.Comment = &v
}

// GetDataChangeCreatedBy returns the DataChangeCreatedBy field value if set, zero value otherwise.
func (o *Releases) GetDataChangeCreatedBy() string {
	if o == nil || o.DataChangeCreatedBy == nil {
		var ret string
		return ret
	}
	return *o.DataChangeCreatedBy
}

// GetDataChangeCreatedByOk returns a tuple with the DataChangeCreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Releases) GetDataChangeCreatedByOk() (*string, bool) {
	if o == nil || o.DataChangeCreatedBy == nil {
		return nil, false
	}
	return o.DataChangeCreatedBy, true
}

// HasDataChangeCreatedBy returns a boolean if a field has been set.
func (o *Releases) HasDataChangeCreatedBy() bool {
	if o != nil && o.DataChangeCreatedBy != nil {
		return true
	}

	return false
}

// SetDataChangeCreatedBy gets a reference to the given string and assigns it to the DataChangeCreatedBy field.
func (o *Releases) SetDataChangeCreatedBy(v string) {
	o.DataChangeCreatedBy = &v
}

// GetDataChangeLastModifiedBy returns the DataChangeLastModifiedBy field value if set, zero value otherwise.
func (o *Releases) GetDataChangeLastModifiedBy() string {
	if o == nil || o.DataChangeLastModifiedBy == nil {
		var ret string
		return ret
	}
	return *o.DataChangeLastModifiedBy
}

// GetDataChangeLastModifiedByOk returns a tuple with the DataChangeLastModifiedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Releases) GetDataChangeLastModifiedByOk() (*string, bool) {
	if o == nil || o.DataChangeLastModifiedBy == nil {
		return nil, false
	}
	return o.DataChangeLastModifiedBy, true
}

// HasDataChangeLastModifiedBy returns a boolean if a field has been set.
func (o *Releases) HasDataChangeLastModifiedBy() bool {
	if o != nil && o.DataChangeLastModifiedBy != nil {
		return true
	}

	return false
}

// SetDataChangeLastModifiedBy gets a reference to the given string and assigns it to the DataChangeLastModifiedBy field.
func (o *Releases) SetDataChangeLastModifiedBy(v string) {
	o.DataChangeLastModifiedBy = &v
}

// GetDataChangeCreatedTime returns the DataChangeCreatedTime field value if set, zero value otherwise.
func (o *Releases) GetDataChangeCreatedTime() string {
	if o == nil || o.DataChangeCreatedTime == nil {
		var ret string
		return ret
	}
	return *o.DataChangeCreatedTime
}

// GetDataChangeCreatedTimeOk returns a tuple with the DataChangeCreatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Releases) GetDataChangeCreatedTimeOk() (*string, bool) {
	if o == nil || o.DataChangeCreatedTime == nil {
		return nil, false
	}
	return o.DataChangeCreatedTime, true
}

// HasDataChangeCreatedTime returns a boolean if a field has been set.
func (o *Releases) HasDataChangeCreatedTime() bool {
	if o != nil && o.DataChangeCreatedTime != nil {
		return true
	}

	return false
}

// SetDataChangeCreatedTime gets a reference to the given string and assigns it to the DataChangeCreatedTime field.
func (o *Releases) SetDataChangeCreatedTime(v string) {
	o.DataChangeCreatedTime = &v
}

// GetDataChangeLastModifiedTime returns the DataChangeLastModifiedTime field value if set, zero value otherwise.
func (o *Releases) GetDataChangeLastModifiedTime() string {
	if o == nil || o.DataChangeLastModifiedTime == nil {
		var ret string
		return ret
	}
	return *o.DataChangeLastModifiedTime
}

// GetDataChangeLastModifiedTimeOk returns a tuple with the DataChangeLastModifiedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Releases) GetDataChangeLastModifiedTimeOk() (*string, bool) {
	if o == nil || o.DataChangeLastModifiedTime == nil {
		return nil, false
	}
	return o.DataChangeLastModifiedTime, true
}

// HasDataChangeLastModifiedTime returns a boolean if a field has been set.
func (o *Releases) HasDataChangeLastModifiedTime() bool {
	if o != nil && o.DataChangeLastModifiedTime != nil {
		return true
	}

	return false
}

// SetDataChangeLastModifiedTime gets a reference to the given string and assigns it to the DataChangeLastModifiedTime field.
func (o *Releases) SetDataChangeLastModifiedTime(v string) {
	o.DataChangeLastModifiedTime = &v
}

func (o Releases) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AppId != nil {
		toSerialize["appId"] = o.AppId
	}
	if o.ClusterName != nil {
		toSerialize["clusterName"] = o.ClusterName
	}
	if o.NamespaceName != nil {
		toSerialize["namespaceName"] = o.NamespaceName
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Configurations != nil {
		toSerialize["configurations"] = o.Configurations
	}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.DataChangeCreatedBy != nil {
		toSerialize["dataChangeCreatedBy"] = o.DataChangeCreatedBy
	}
	if o.DataChangeLastModifiedBy != nil {
		toSerialize["dataChangeLastModifiedBy"] = o.DataChangeLastModifiedBy
	}
	if o.DataChangeCreatedTime != nil {
		toSerialize["dataChangeCreatedTime"] = o.DataChangeCreatedTime
	}
	if o.DataChangeLastModifiedTime != nil {
		toSerialize["dataChangeLastModifiedTime"] = o.DataChangeLastModifiedTime
	}
	return json.Marshal(toSerialize)
}

type NullableReleases struct {
	value *Releases
	isSet bool
}

func (v NullableReleases) Get() *Releases {
	return v.value
}

func (v *NullableReleases) Set(val *Releases) {
	v.value = val
	v.isSet = true
}

func (v NullableReleases) IsSet() bool {
	return v.isSet
}

func (v *NullableReleases) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReleases(val *Releases) *NullableReleases {
	return &NullableReleases{value: val, isSet: true}
}

func (v NullableReleases) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReleases) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
